version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: genomic-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: genomic-data-mesh
    volumes:
      - mongodb_data:/data/db
      - ./data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - genomic-network

  # Backend API
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: genomic-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/genomic-data-mesh?authSource=admin
      HEDERA_OPERATOR_ID: ${HEDERA_OPERATOR_ID:-0.0.123456}
      HEDERA_OPERATOR_KEY: ${HEDERA_OPERATOR_KEY}
      HEDERA_CONSENT_TOPIC_ID: ${HEDERA_CONSENT_TOPIC_ID}
      HEDERA_GENOMIC_TOPIC_ID: ${HEDERA_GENOMIC_TOPIC_ID}
    depends_on:
      - mongodb
    networks:
      - genomic-network
    volumes:
      - ./server/uploads:/app/uploads

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genomic-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_HEDERA_NETWORK: testnet
    depends_on:
      - backend
    networks:
      - genomic-network

volumes:
  mongodb_data:

networks:
  genomic-network:
    driver: bridge
