export const METAMASK_GAS_LIMIT_ASSOCIATE = 800_000;
export const METAMASK_GAS_LIMIT_TRANSFER_FT = 50_000;
export const METAMASK_GAS_LIMIT_TRANSFER_NFT = 100_000;

// Hedera Configuration
export const HEDERA_CONFIG = {
  // Token IDs
  RESEARCH_CONSENT_NFT_TOKEN_ID:
    process.env.REACT_APP_HEDERA_RESEARCH_CONSENT_NFT_ID || "0.0.6894104",
  PASSPORT_NFT_TOKEN_ID:
    process.env.REACT_APP_HEDERA_PASSPORT_NFT_ID || "0.0.6894105",
  DATA_SYNC_NFT_TOKEN_ID:
    process.env.REACT_APP_HEDERA_DATA_SYNC_NFT_ID || "0.0.6894106",
  RDZ_INCENTIVE_TOKEN_ID:
    process.env.REACT_APP_HEDERA_RDZ_INCENTIVE_TOKEN_ID || "0.0.6894102",

  // Topic IDs (if needed in frontend)
  RESEARCH_CONSENT_TOPIC_ID:
    process.env.REACT_APP_HEDERA_RESEARCH_CONSENT_TOPIC_ID || "0.0.6894099",
  PASSPORT_TOPIC_ID:
    process.env.REACT_APP_HEDERA_PASSPORT_TOPIC_ID || "0.0.6894101",
  DATA_SYNC_TOPIC_ID:
    process.env.REACT_APP_HEDERA_DATA_SYNC_TOPIC_ID || "0.0.6894100",
} as const;
